### ISSUE TITLE
unresolved dependency: com.typesafe.sbteclipse#sbteclipse-plugin;2.1.1: not found

### ISSUE THREAD

**Issue by vnicolici** [sbt/sbt-eclipse#148]
I tried to create a simple sbt eclipse project, and this is the result:

```
C:\Users\Vladimir\scalaworkspace\backup-tool>sbt
[info] Loading project definition from C:\Users\Vladimir\scalaworkspace\backup-tool\project
[info] Updating {file:/C:/Users/Vladimir/scalaworkspace/backup-tool/project/}default-1b3502...
[info] Resolving com.typesafe.sbteclipse#sbteclipse-plugin;2.1.1 ...
[warn]  module not found: com.typesafe.sbteclipse#sbteclipse-plugin;2.1.1
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.10/sbt_0.12/2.1.1/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.10/sbt_0.12/2.1.1/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\Vladimir\.ivy2\local\com.typesafe.sbteclipse\sbteclipse-plugin\scala_2.10\sbt_0.12\2.1.1\ivys\ivy.xml
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/typesafe/sbteclipse/sbteclipse-plugin_2.10_0.12/2.1.1/sbteclipse-plugin-2.1.1.pom
[info] Resolving org.scala-sbt#sbt;0.12.1 ...
  [info] Resolving org.scala-sbt#main;0.12.1 ...
  [info] Resolving org.scala-sbt#actions;0.12.1 ...
  [info] Resolving org.scala-sbt#classpath;0.12.1 ...
  [info] Resolving org.scala-sbt#launcher-interface;0.12.1 ...
  [info] Resolving org.scala-lang#scala-library;2.10.0 ...
  [info] Resolving org.scala-sbt#interface;0.12.1 ...
  [info] Resolving org.scala-sbt#io;0.12.1 ...
  [info] Resolving org.scala-sbt#control;0.12.1 ...
  [info] Resolving org.scala-lang#scala-compiler;2.10.0 ...
  [info] Resolving org.scala-lang#scala-reflect;2.10.0 ...
  [info] Resolving org.scala-sbt#completion;0.12.1 ...
  [info] Resolving org.scala-sbt#collections;0.12.1 ...
  [info] Resolving jline#jline;1.0 ...
  [info] Resolving org.scala-sbt#api;0.12.1 ...
  [info] Resolving org.scala-sbt#compiler-integration;0.12.1 ...
  [info] Resolving org.scala-sbt#incremental-compiler;0.12.1 ...
  [info] Resolving org.scala-sbt#logging;0.12.1 ...
  [info] Resolving org.scala-sbt#process;0.12.1 ...
  [info] Resolving org.scala-sbt#compile;0.12.1 ...
  [info] Resolving org.scala-sbt#persist;0.12.1 ...
  [info] Resolving org.scala-tools.sbinary#sbinary_2.9.0;0.4.0 ...
  [info] Resolving org.scala-sbt#classfile;0.12.1 ...
  [info] Resolving org.scala-sbt#compiler-ivy-integration;0.12.1 ...
  [info] Resolving org.scala-sbt#ivy;0.12.1 ...
  [info] Resolving org.apache.ivy#ivy;2.3.0-rc1 ...
  [info] Resolving com.jcraft#jsch;0.1.46 ...
  [info] Resolving commons-httpclient#commons-httpclient;3.1 ...
  [info] Resolving commons-logging#commons-logging;1.0.4 ...
  [info] Resolving commons-codec#commons-codec;1.2 ...
  [info] Resolving org.scala-sbt#run;0.12.1 ...
  [info] Resolving org.scala-sbt#task-system;0.12.1 ...
  [info] Resolving org.scala-sbt#tasks;0.12.1 ...
  [info] Resolving org.scala-sbt#tracking;0.12.1 ...
  [info] Resolving org.scala-sbt#cache;0.12.1 ...
  [info] Resolving org.scala-sbt#testing;0.12.1 ...
  [info] Resolving org.scala-sbt#test-agent;0.12.1 ...
  [info] Resolving org.scala-tools.testing#test-interface;0.5 ...
  [info] Resolving org.scala-sbt#command;0.12.1 ...
  [info] Resolving org.scala-sbt#compiler-interface;0.12.1 ...
  [info] Resolving org.scala-sbt#precompiled-2_8_2;0.12.1 ...
  [info] Resolving org.scala-sbt#precompiled-2_10_0-m7;0.12.1 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.typesafe.sbteclipse#sbteclipse-plugin;2.1.1: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.typesafe.sbteclipse:sbteclipse-plugin:2.1.1 (sbtVersion=0.12, scalaVersion=2.10)
[warn]
sbt.ResolveException: unresolved dependency: com.typesafe.sbteclipse#sbteclipse-plugin;2.1.1: not found
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:214)
        at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:122)
        at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:121)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:114)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:114)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:102)
        at sbt.IvySbt.liftedTree1$1(Ivy.scala:49)
        at sbt.IvySbt.action$1(Ivy.scala:49)
        at sbt.IvySbt$$anon$3.call(Ivy.scala:58)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:75)
        at xsbt.boot.Locks$GlobalLock.withChannelRetries$1(Locks.scala:58)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:79)
        at xsbt.boot.Using$.withResource(Using.scala:11)
        at xsbt.boot.Using$.apply(Using.scala:10)
        at xsbt.boot.Locks$GlobalLock.liftedTree1$1(Locks.scala:51)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:51)
        at xsbt.boot.Locks$.apply0(Locks.scala:30)
        at xsbt.boot.Locks$.apply(Locks.scala:27)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:58)
        at sbt.IvySbt.withIvy(Ivy.scala:99)
        at sbt.IvySbt.withIvy(Ivy.scala:95)
        at sbt.IvySbt$Module.withModule(Ivy.scala:114)
        at sbt.IvyActions$.update(IvyActions.scala:121)
        at sbt.Classpaths$$anonfun$work$1$1.apply(Defaults.scala:951)
        at sbt.Classpaths$$anonfun$work$1$1.apply(Defaults.scala:949)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$54.apply(Defaults.scala:972)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$54.apply(Defaults.scala:970)
        at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:974)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:969)
        at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
        at sbt.Classpaths$.cachedUpdate(Defaults.scala:977)
        at sbt.Classpaths$$anonfun$45.apply(Defaults.scala:856)
        at sbt.Classpaths$$anonfun$45.apply(Defaults.scala:853)
        at sbt.Scoped$$anonfun$hf10$1.apply(Structure.scala:586)
        at sbt.Scoped$$anonfun$hf10$1.apply(Structure.scala:586)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:49)
        at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
        at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:41)
        at sbt.std.Transform$$anon$5.work(System.scala:71)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.Execute.work(Execute.scala:238)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
        at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[error] (*:update) sbt.ResolveException: unresolved dependency: com.typesafe.sbteclipse#sbteclipse-plugin;2.1.1: not found
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

build.properties:

```
sbt.version=0.12.1
```

build.sbt:

```
name := "hello"

version := "1.0"

scalaVersion := "2.10.0" 
```

plugins.sbt:

```
addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "2.1.1")
```

**Comment by hugith** [comment]
I'm having the same problem with sbteclipse. Do I ned to downgrade to Scala 2.10?

**Comment by dragos** [comment]
No, but please double-check your dependency (particularly, the directory where your `plugins.sbt` is). Sbt makes it easy to add it to the wrong place. Also, make sure you're using a recent version of Sbt (latest one is 0.13.8).

**Comment by nickshen3** [comment]
addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "2.5.0")

**Comment by facundoq** [comment]
Would it be possible to list the supported Scala versions in the home page? I've been scratching my head for the last hour until I found this post and downgraded to scala 2.10. 

Given that the latest stable versions of scala and sbt you can download are 2.11.7 and 0.13.9, that they both work fine together, and that the home page says sbt 0.13.9 is supported, it's nigh impossible to figure out the error.

Also, the home (https://github.com/typesafehub/sbteclipse) and installation (https://github.com/typesafehub/sbteclipse/wiki/Installing-sbteclipse) pages mention different sbteclipse versions (4 vs 2.5)

Thanks!

**Comment by porks** [comment]
what did the trick for me was:

in plugins.sbt:
addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "2.5.0")

in build.sbt:
resolvers += Classpaths.typesafeResolver

libraryDependencies += "org.scala-lang.modules" %% "scala-java8-compat" % "0.2.0"

**Comment by joney000** [comment]
remove ~/.sbt/boot/sbt.boot.lock and again try . It worked for me.

**Comment by patilnikki** [comment]
add the newer version it worked for me.
~/project/plugin.sbt 

`addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "5.2.4")`
